# Generated by Django 3.0.6 on 2020-05-17 13:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grps', '0002_auto_20200517_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[], size=5)),
                ('email_list', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100), default=[], size=5)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AddField(
            model_name='person',
            name='email_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100), default=[], size=5),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[], size=5),
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_bread_included', models.BooleanField(default=True)),
                ('is_tip_included', models.BooleanField(default=False)),
                ('appetizer_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('soup_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('salad_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('main_dish_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('dessert_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('drink_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('cost', models.FloatField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.Restaurant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
