# Generated by Django 3.0.6 on 2020-05-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grps', '0005_auto_20200518_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantreservation',
            options={'ordering': ['group']},
        ),
    ]
