# Generated by Django 3.0.6 on 2020-05-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grps', '0006_auto_20200519_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupDetails',
            new_name='GroupDetail',
        ),
    ]
