# Generated by Django 3.0.6 on 2020-05-21 07:59

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grps', '0011_auto_20200519_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('stars', models.PositiveSmallIntegerField()),
                ('rooms', models.PositiveSmallIntegerField()),
                ('floors', models.PositiveSmallIntegerField()),
                ('elevators', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, size=5)),
                ('email_list', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100), blank=True, default=list, size=5)),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5)),
            ],
            options={
                'ordering': ['city', 'stars'],
            },
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateField(default=datetime.date.today)),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.GroupDetail')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.Hotel')),
            ],
            options={
                'ordering': ['group', 'hotel'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('SGL', 'Single Room'), ('TWN', 'Twin Room'), ('TRP', 'Triple Room'), ('QTR', '4-Bed Room'), ('SUI', 'Suite'), ('SPE', 'Special Room')], default='TWN', max_length=3)),
                ('meal_plan', models.CharField(choices=[('NO', 'No Meal'), ('BB', 'Bead & Breakfast'), ('HB', 'Half-Board'), ('FB', 'Full-Board'), ('AI', 'All-Inclusive')], default='BB', max_length=2)),
                ('staying_date', models.DateField(default=datetime.date.today)),
                ('rate_per_room', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5)),
                ('hotel_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.HotelReservation')),
            ],
            options={
                'ordering': ['hotel_reservation'],
            },
        ),
        migrations.CreateModel(
            name='HotelDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5)),
                ('hotel_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.HotelReservation')),
            ],
            options={
                'ordering': ['deposit_date'],
            },
        ),
    ]
