# Generated by Django 3.0.6 on 2020-05-23 08:28

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grps', '0013_auto_20200523_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='restaurantmenu',
            options={'ordering': ['restaurant']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['city', 'name']},
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='restaurantreservation',
            name='extra_cost',
        ),
        migrations.RemoveField(
            model_name='site',
            name='transportationMean',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='title',
            field=models.CharField(default='Tour Guide', max_length=50, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='restaurantreservation',
            name='extra_payment',
            field=models.DecimalField(decimal_places=1, help_text='Payment for emergency reasons', max_digits=5, null=True, verbose_name='Extra Payment'),
        ),
        migrations.AlterField(
            model_name='groupdetail',
            name='group_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grps.GroupName', verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='departure_date',
            field=models.DateField(default=datetime.date.today, help_text='Date mentioned in the request email', verbose_name='Departure Date'),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='name',
            field=models.CharField(help_text='Name mentioned in the request email', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='elevators',
            field=models.PositiveSmallIntegerField(verbose_name='Elevators'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Email List'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='extra_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='floors',
            field=models.PositiveSmallIntegerField(help_text='Number of floors that rooms are distributed', verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, size=5, verbose_name='Phone List'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rooms',
            field=models.PositiveSmallIntegerField(help_text='Total number of rooms', verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.PositiveSmallIntegerField(verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='hoteldeposit',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='hoteldeposit',
            name='deposit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Deposit Date'),
        ),
        migrations.AlterField(
            model_name='hoteldeposit',
            name='extra_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes'),
        ),
        migrations.AlterField(
            model_name='hoteldeposit',
            name='hotel_reservation',
            field=models.ForeignKey(help_text='Choose hotel reservation from the list', on_delete=django.db.models.deletion.CASCADE, to='grps.HotelReservation', verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='confirmation_date',
            field=models.DateField(help_text='The date that the hotel confirmed the reservation', null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='extra_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes'),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.GroupDetail', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.Hotel', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='extra_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes'),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='hotel_reservation',
            field=models.ForeignKey(help_text='Choose hotel reservation from the list', on_delete=django.db.models.deletion.CASCADE, to='grps.HotelReservation', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='meal_plan',
            field=models.CharField(choices=[('NO', 'No Meal'), ('BB', 'Bead & Breakfast'), ('HB', 'Half-Board'), ('FB', 'Full-Board'), ('AI', 'All-Inclusive')], default='BB', max_length=2, verbose_name='Meal Plan'),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='quantity',
            field=models.PositiveSmallIntegerField(help_text='Number of rooms required', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='rate_per_room',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='room_type',
            field=models.CharField(choices=[('SGL', 'Single Room'), ('TWN', 'Twin Room'), ('TRP', 'Triple Room'), ('QTR', '4-Bed Room'), ('SUI', 'Suite'), ('SPE', 'Special Room')], default='TWN', max_length=3, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='hotelroomreservation',
            name='staying_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Staying Date'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='person',
            name='emailList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Email List'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extraNotes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='jobPosition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.JobPosition', verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, size=5, verbose_name='Phone List'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Email List'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='extra_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, size=5, verbose_name='Phone List'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='appetizer_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Appetizers'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='cost_per_person',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=5, verbose_name='Cost/Person'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='dessert_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Desserts'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='drink_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Drinks'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='extra_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='is_bread_included',
            field=models.BooleanField(default=True, verbose_name='Bread Included'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='is_tip_included',
            field=models.BooleanField(default=False, verbose_name='Tip Included'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='main_dish_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Main Dishes'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='restaurant',
            field=models.ForeignKey(help_text='Choose Restaurant', on_delete=django.db.models.deletion.CASCADE, to='grps.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='salad_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Salads'),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='soup_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Soups'),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='extra_notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes'),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='free_pax',
            field=models.PositiveSmallIntegerField(verbose_name='Free Meals'),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='group',
            field=models.ForeignKey(help_text='Choose a group from the list', on_delete=django.db.models.deletion.CASCADE, to='grps.GroupDetail', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date | Time'),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='restaurant_menu',
            field=models.ForeignKey(help_text='Choose a menu from the list', on_delete=django.db.models.deletion.CASCADE, to='grps.RestaurantMenu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='restaurantreservation',
            name='total_pax',
            field=models.PositiveSmallIntegerField(help_text='Total meals served', verbose_name='Total PAX'),
        ),
        migrations.AlterField(
            model_name='site',
            name='city',
            field=models.CharField(help_text='Main city where the site is located', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='Name of the site visited', max_length=100, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('arrival_time', models.TimeField(null=True, verbose_name='Arrival Time')),
                ('departure_time', models.TimeField(null=True, verbose_name='Departure Time')),
                ('transportation_mean', models.CharField(choices=[('BUS', 'Bus'), ('FER', 'Ferry'), ('AIR', 'Airplane'), ('TRA', 'Train'), ('WAL', 'Walk'), ('TEL', 'Teleferik'), ('KAT', 'Katamaran')], default='BUS', max_length=3, verbose_name='Transportation Mean')),
                ('entrance_fee', models.PositiveSmallIntegerField(verbose_name='Entrance Fee')),
                ('participating_clients', models.PositiveSmallIntegerField(verbose_name='Participating Clients')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
                ('group', models.ForeignKey(help_text='Choose a group from the list', on_delete=django.db.models.deletion.CASCADE, to='grps.GroupDetail', verbose_name='Group')),
                ('site', models.ForeignKey(help_text='Choose a site from the list', on_delete=django.db.models.deletion.CASCADE, to='grps.Site', verbose_name='Site')),
            ],
            options={
                'ordering': ['site', 'date'],
            },
        ),
    ]
