# Generated by Django 3.0.6 on 2020-05-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grps', '0014_auto_20200523_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdetail',
            name='is_tour_leader',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='pax',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='tour_guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grps.Person', verbose_name='Tour Guide'),
        ),
    ]
