# Generated by Django 3.0.6 on 2020-05-30 11:00

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grps', '0016_auto_20200530_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the site visited', max_length=100, verbose_name='Name')),
                ('city', models.CharField(help_text='Main city where the site is located', max_length=50, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('arrival_time', models.TimeField(null=True, verbose_name='Arrival Time')),
                ('departure_time', models.TimeField(null=True, verbose_name='Departure Time')),
                ('transportation_mean', models.CharField(choices=[('BUS', 'Bus'), ('FER', 'Ferry'), ('AIR', 'Airplane'), ('TRA', 'Train'), ('WAL', 'Walk'), ('TEL', 'Teleferik'), ('KAT', 'Katamaran')], default='BUS', max_length=3, verbose_name='Transportation Mean')),
                ('entrance_fee', models.PositiveSmallIntegerField(verbose_name='Entrance Fee')),
                ('participating_clients', models.PositiveSmallIntegerField(verbose_name='Participating Clients')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
                ('group', models.ForeignKey(help_text='Choose a group from the list', on_delete=django.db.models.deletion.CASCADE, to='grps.GroupDetail', verbose_name='Group')),
                ('site', models.ForeignKey(help_text='Choose a site from the list', on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visits',
                'ordering': ['site', 'date'],
            },
        ),
    ]
