# Generated by Django 3.0.6 on 2020-05-30 11:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grps', '0016_auto_20200530_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('phone_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, size=5, verbose_name='Phone List')),
                ('email_list', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Email List')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_bread_included', models.BooleanField(default=True, verbose_name='Bread Included')),
                ('is_tip_included', models.BooleanField(default=False, verbose_name='Tip Included')),
                ('appetizer_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Appetizers')),
                ('soup_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Soups')),
                ('salad_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Salads')),
                ('main_dish_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Main Dishes')),
                ('dessert_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Desserts')),
                ('drink_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=5, verbose_name='Drinks')),
                ('cost_per_person', models.DecimalField(decimal_places=1, default=10.0, max_digits=5, verbose_name='Cost/Person')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
                ('restaurant', models.ForeignKey(help_text='Choose Restaurant', on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Menu',
                'verbose_name_plural': 'Restaurant Menus',
                'ordering': ['restaurant'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date | Time')),
                ('total_pax', models.PositiveSmallIntegerField(help_text='Total meals served', verbose_name='Total PAX')),
                ('free_pax', models.PositiveSmallIntegerField(verbose_name='Free Meals')),
                ('extra_payment', models.DecimalField(decimal_places=1, help_text='Payment for emergency reasons', max_digits=5, null=True, verbose_name='Extra Payment')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
                ('group', models.ForeignKey(help_text='Choose a group from the list', on_delete=django.db.models.deletion.CASCADE, to='grps.GroupDetail', verbose_name='Group')),
                ('restaurant_menu', models.ForeignKey(help_text='Choose a menu from the list', on_delete=django.db.models.deletion.CASCADE, to='restaurants.RestaurantMenu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Restaurant Reservation',
                'verbose_name_plural': 'Restaurant Reservations',
                'ordering': ['group'],
            },
        ),
    ]
