# Generated by Django 3.0.6 on 2020-05-30 11:00

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grps', '0016_auto_20200530_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='Stars')),
                ('rooms', models.PositiveSmallIntegerField(help_text='Total number of rooms', verbose_name='Rooms')),
                ('floors', models.PositiveSmallIntegerField(help_text='Number of floors that rooms are distributed', verbose_name='Floors')),
                ('elevators', models.PositiveSmallIntegerField(verbose_name='Elevators')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('phone_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, size=5, verbose_name='Phone List')),
                ('email_list', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Email List')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['city', 'stars'],
            },
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateField(help_text='The date that the hotel confirmed the reservation', null=True, verbose_name='Confirmation Date')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grps.GroupDetail', verbose_name='Group')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Reservation',
                'verbose_name_plural': 'Hotel Reservations',
                'ordering': ['group', 'hotel'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('SGL', 'Single Room'), ('TWN', 'Twin Room'), ('TRP', 'Triple Room'), ('QTR', '4-Bed Room'), ('SUI', 'Suite'), ('SPE', 'Special Room')], default='TWN', max_length=3, verbose_name='Room Type')),
                ('meal_plan', models.CharField(choices=[('NO', 'No Meal'), ('BB', 'Bead & Breakfast'), ('HB', 'Half-Board'), ('FB', 'Full-Board'), ('AI', 'All-Inclusive')], default='BB', max_length=2, verbose_name='Meal Plan')),
                ('staying_date', models.DateField(default=datetime.date.today, verbose_name='Staying Date')),
                ('rate_per_room', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Rate')),
                ('quantity', models.PositiveSmallIntegerField(help_text='Number of rooms required', verbose_name='Quantity')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
                ('hotel_reservation', models.ForeignKey(help_text='Choose hotel reservation from the list', on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelReservation', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel Room Reservation',
                'verbose_name_plural': 'Hotel Room Reservations',
                'ordering': ['hotel_reservation'],
            },
        ),
        migrations.CreateModel(
            name='HotelDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField(default=datetime.date.today, verbose_name='Deposit Date')),
                ('amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Amount')),
                ('extra_notes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=5, verbose_name='Extra Notes')),
                ('hotel_reservation', models.ForeignKey(help_text='Choose hotel reservation from the list', on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelReservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Hotel Deposit',
                'verbose_name_plural': 'Hotel Deposits',
                'ordering': ['deposit_date'],
            },
        ),
    ]
